[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[font]
size = 16

[font.normal]
family = "Roboto Mono Nerd Font"

[font.bold]
family = "Roboto Mono Nerd Font"

[font.italic]
family = "Roboto Mono Nerd Font"

[font.bold_italic]
family = "Roboto Mono Nerd Font"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
opacity = 0.95
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[general]
import = ["monokai_charcoal.toml"]
